logs:
  - name: root
    level: debug
    appenders:
      - type: FileLogAppender
        path: log/gateway_http/root.log
        rotate_type: hour
      - type: StdoutLogAppender
        
  - name: system
    level: info
    appenders:
      - type: FileLogAppender
        path: log/gateway_http/system.log
        rotate_type: size
        max_size: 10485760
      - type: StdoutLogAppender